title: Codebase

author: Gemar Kode

description: "Open Source Code Snippets, Algorithm Examples, and Design Pattern examples."

baseurl: ""

permalink: /:title

url: "http://127.0.0.1:4000"

plugins:
  - jekyll-feed