title: Codebase

author: Gemar Kode

description: "Codebase is an Open Source Code Snippet. Save Algorithms, code Snippets and Design Pattern examples."

baseurl: ""

permalink: /:title

url: "http://127.0.0.1:4000"

plugins:
  - jekyll-feed