title: Codebase

author: Gemar Kode

description: "Open Source Code Snippets, Algorithm Examples, and Design Pattern examples."

baseurl: ""

permalink: /:title

url: "https://codebase.gemarkode.or.id"

plugins:
  - jekyll-feed
